### ISSUE TITLE
Spaces in file names

### ISSUE THREAD

**Issue by Criyl** [CarrollGram2009/hello-world#1]
As a general rule of thumb having spaces in your file names is a no no. 

Two popular naming conventions are CamelCase and snake_case. 

# snake_case
 - lowercase letters with spaces denoted as underscores
 
# camelCase
- first letter of words are capitalized with no spaces. With certain rules about when the first letter should and shouldnt be capitalized

These are usually used in variables but can carry into file names as well.

**Comment by CarrollGram2009** [comment]
I have fixed this issue
