### ISSUE TITLE
Link mismatch

### ISSUE THREAD

**Issue by Criyl** [CarrollGram2009/hello-world#2]
The link to download php in your README appears to be the link to download R but the hyperlink seems to be working.

**Comment by CarrollGram2009** [comment]
fixed

**Comment by Criyl** [comment]
Another thing that would help you is the concept we call branching. The idea being that for every change you want to make you create a new branch which is like a little off shoot of your project with only the things you want changed. You can then add those changes back into the main/master branch after they are completed without effecting your existing project.

**Comment by Criyl** [comment]
You can click on Development on the right of this ticket and it will prompt you to create a branch attached to this ticket. This is just great for organization and must have if youre collaborating with other developers.

**Comment by Criyl** [comment]
Once you have the changes on your branch how you want them there is something we call a pull request (sometimes called a merge request) that usually will go through a peer review and/or a battery of automated tests before being allowed to be brought into the main branch.

**Comment by CarrollGram2009** [comment]
thanks for the suggestion
