### ISSUE TITLE
File structure suggestion

### ISSUE THREAD

**Issue by Criyl** [CarrollGram2009/hello-world#3]
Something I would do, is rather than have everything in one folder. Have something like the following.
```
ruby/
├─ README.md
├─ helloworld.rb
php/
├─ README.md
├─ helloworld.php
R/
├─ helloworld.r
├─ README.md
README.md (For a general introduction to the project)
```

This keeps it clean, and leaves space to add more languages in the future.

**Comment by CarrollGram2009** [comment]
I organized all the files for you
